### ISSUE TITLE
Getting 'Cross-Origin Request Blocked' on a GET request using Axios

### ISSUE THREAD

**Issue by webdevsuperfast** [yausername/NewPipeREST#2]
@yausername ,

Thank you for the REST API for NewPipe however I get `Cross-Origin Request Blocked` issue. Here's my [code](https://github.com/webdevsuperfast/youtube-search-app/tree/develop) and the [development site](https://inspiring-ardinghelli-35a422.netlify.com/). Not sure if this is an Axios [issue](https://github.com/axios/axios/issues/853) or not. Tried using `fetch` to no avail also :)

Thanks!

**Comment by yausername** [comment]
Hi @webdevsuperfast ,
I have enabled CORS support. Please check now.
Thanks!
