### ISSUE TITLE
How this work?

### ISSUE THREAD

**Issue by limaho** [yausername/NewPipeREST#4]
I trying using the link provided in the doc but is blank? How can I extract the stream url of a video? Thanks

**Comment by yausername** [comment]
Hi,
You can use the try it out button on https://app.swaggerhub.com/apis-docs/yayausername/new-pipe_rest/1.0.0 to know how it works.
For example to get the stream info of https://www.youtube.com/watch?v=zTxxlPGohz0 url, you should use the following url https://newpipe-rest.herokuapp.com/api/v1/streams?url=https://www.youtube.com/watch?v=zTxxlPGohz0
